version: '3.8'

services:
  yolo-flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - TORCH_NUM_THREADS=1
    volumes:
      - ./backend/static:/home/app/backend/static
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
